apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: myapp-container
    image: nginx
    ports:
    - containerPort: 80
  - name: logger-sidecar
    image: busybox
    args: ["/bin/sh", "-c", 'while true; do sleep 30; echo "$(date) - Still running"; done']
    volumeMounts:
    - name: log-volume
      mountPath: /var/log/myapp
  initContainers:
  - name: init-myservice
    image: busybox
    command: ['sh', '-c', 'echo Initializing application...; sleep 5']
    volumeMounts:
    - name: log-volume
      mountPath: /var/log/myapp
  volumes:
  - name: log-volume
    emptyDir: {}
